version: "3.9"
services:
  db:
    container_name: fight_master_db_test
    image: postgres:latest
    restart: always
    env_file:
      - ./env/db/db.env
    user: postgres
    volumes:
      - ./fight_master_db.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "35000:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: fight_master_app_test
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - ./env/app/test.env
    ports:
      - "3001:3001"
      - "9229:9229"
